<?php
namespace MarineVideoPortal\Bunny;
class BunnyService {
  private string $libId; private string $apiKey; private string $tokenKey; private string $cdnHost;
  public function __construct(){ $this->libId=$_ENV['BUNNY_LIBRARY_ID']??''; $this->apiKey=$_ENV['BUNNY_API_KEY']??''; $this->tokenKey=$_ENV['BUNNY_TOKEN_AUTH_KEY']??''; $this->cdnHost=$_ENV['BUNNY_CDN_HOSTNAME']??''; }
  private function req($m,$p,$b=null){$url="https://video.bunnycdn.com/library/{$this->libId}$p";$ch=curl_init($url);$h=["AccessKey: {$this->apiKey}","Content-Type: application/json"];curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>$h,CURLOPT_CUSTOMREQUEST=>$m]);if($b!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($b));$r=curl_exec($ch);$c=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($c>=400)throw new \Exception("Bunny $c $r URL $url");return json_decode($r,true)??[];}
  public function listVideos($page=1,$per=100){return $this->req('GET',"/videos?page=$page&itemsPerPage=$per&orderBy=date");}
  public function deleteVideo($g){return $this->req('DELETE',"/videos/$g");}
  public function signedEmbedUrl($g,$ttl=14400){$e=time()+$ttl;$t=hash('sha256',$this->tokenKey.$g.$e);return "https://iframe.mediadelivery.net/embed/{$this->libId}/$g?token=$t&expires=$e&autoplay=false";}
  public function thumbnailUrl($g,$ttl=86400){$e=time()+$ttl;if($this->tokenKey){$t=hash('sha256',$this->tokenKey.$g.$e);if($this->cdnHost)return "https://{$this->cdnHost}/$g/thumbnail.jpg?token=$t&expires=$e";return "https://iframe.mediadelivery.net/{$this->libId}/$g/thumbnail.jpg?token=$t&expires=$e";}if($this->cdnHost)return "https://{$this->cdnHost}/$g/thumbnail.jpg";return "https://iframe.mediadelivery.net/{$this->libId}/$g/preview.jpg";}
  public function syncToDb():int{$cnt=0;$p=1;do{$resp=$this->listVideos($p,100);$items=$resp['items']??[];if(empty($items))break;foreach($items as $v){$guid=$v['guid']??'';if(!$guid)continue;$title=$v['title']??'Untitled';$col=$v['collectionId']??null;$ex=\MarineVideoPortal\Core\Database::fetchOne("SELECT guid FROM videos_meta WHERE guid=?",[$guid]);if($ex){\MarineVideoPortal\Core\Database::exec("UPDATE videos_meta SET title=? WHERE guid=?",[$title,$guid]);}else{\MarineVideoPortal\Core\Database::exec("INSERT INTO videos_meta (guid,collection_id,title,watermark_mode,custom_order) VALUES (?,?,?,?,0)",[$guid,$col,$title,'default']);}$cnt++;}if(count($items)<100)break;$p++;}while(true);return $cnt;}
}
